name: Terraform lint and terrascan

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: terraform validate
        uses: hashicorp/setup-terraform@v2.0.3
        run: terraform validate
      
      - name: run tflint
        uses: terraform-linters/setup-tflint@v5.0.0 
        run: tflint terraform

      # - name: run tfsec
      #   uses: Flydiverny/setup-tfsec@v1
      #   # run: tfsec .

      - name: terrascan
        uses: tenable/terrascan-action@v1.4.1
      

        
